### ISSUE TITLE
Seeking new maintainer(s)

### ISSUE THREAD

**Issue by blooddy** [blooddy/blooddy_crypto#55]
[![Seeking new maintainer(s)](https://img.shields.io/badge/%E2%9A%A0-seeking_new_maintainer%28s%29-orange.svg)](https://github.com/blooddy/blooddy_crypto/issues/55)
--------------------------------------
There are complaints about the work of the library on the IOS device.
I do not have such devices. Please help with debug.

Issues:
- [x] #17 SHA hashing returning different values on mobile/desktop

**Comment by illuzor** [comment]
Могу проверить. Что именно нужно сделать?

**Comment by blooddy** [comment]
Пишут что MD5 и SHA на маках считается не правильно. Надо продебажить и понять чем маки особенные

**Comment by illuzor** [comment]
Проверил на винде, на ios и на android (функцию взял из #17 )
Всё абсоютно одинаково.
Версия библиотеки 0.53 (из релиза), AIR 22.97, win 10, ios 9.3.1, android 6.0.1/5.1.1

**Comment by blooddy** [comment]
Имеется ввиду native сборка под мобилу.

**Comment by illuzor** [comment]
Что понимается под native сборкой?

**Comment by blooddy** [comment]
http://help.adobe.com/en_US/air/build/WSfffb011ac560372f-5d0f4f25128cc9cd0cb-8000.html

**Comment by illuzor** [comment]
Это ясно. Кажется, мы друг друга не поняли. Я собрал ipa для ios и apk для android(ну и собственно запустил на соответствующих девайсах), дополнительно запустил через adl на винде - результат выполнения функции из #17 во всех случаях одинаков.

**Comment by blooddy** [comment]
ну ок. пускай пока что ещё повисит =) может ещё кто появится. спасибо!
